# Generated by Django 4.0.2 on 2022-02-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=20)),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
