# Generated by Django 4.0.2 on 2022-02-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review_tag', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('patient', 'patient'), ('new_patient', 'new_patient'), ('partially_recovered', 'partially_recovered'), ('fully_recovered', 'fully_recovered')], default=1, max_length=30)),
            ],
        ),
    ]
