# Generated by Django 4.0.2 on 2022-02-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reviews_options_rename_avatar_reviews_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='image',
            new_name='avatar',
        ),
    ]
