# Generated by Django 4.0.2 on 2022-02-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_image_reviews_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='avatar',
            new_name='image',
        ),
    ]
